---
- name: "Mailerconf: Configure /etc/mail/mailer.conf"
  ansible.builtin.template:
    src: mailer.conf.j2
    dest: /etc/mail/mailer.conf
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ fm_ssmtp_backup_conf }}"

# EOF
