---
# tasks for freebsd_ssmtp

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: fm_ssmtp_debug | bool
  tags: fm_ssmtp_debug

- name: Import pkg.yml
  ansible.builtin.import_tasks: pkg.yml
  when: fm_ssmtp_install | bool
  tags: fm_ssmtp_pkg

- name: Import rcconf.yml
  ansible.builtin.import_tasks: rcconf.yml
  tags: fm_ssmtp_rcconf

- name: Import mailerconf.yml
  ansible.builtin.import_tasks: mailerconf.yml
  tags: fm_ssmtp_mailerconf

- name: Import periodicconf.yml
  ansible.builtin.import_tasks: periodicconf.yml
  tags: fm_ssmtp_periodicconf

- name: Import config.yml
  ansible.builtin.import_tasks: config.yml
  tags: fm_ssmtp_config

# EOF
