---
# tasks for freebsd_ssmtp

- ansible.builtin.import_tasks: debug.yml
  when: fm_ssmtp_debug|bool
  tags: fm_ssmtp_debug

- ansible.builtin.import_tasks: packages.yml
  when: fm_ssmtp_install|bool
  tags: fm_ssmtp_packages

- ansible.builtin.import_tasks: rcconf.yml
  tags: fm_ssmtp_rcconf

- ansible.builtin.import_tasks: mailerconf.yml
  tags: fm_ssmtp_mailerconf

- ansible.builtin.import_tasks: periodicconf.yml
  tags: fm_ssmtp_periodicconf

- ansible.builtin.import_tasks: config.yml
  tags: fm_ssmtp_config

# EOF
