---

- name: "periodic: Configure /etc/periodic.conf.local"
  ansible.builtin.lineinfile:
    dest: /etc/periodic.conf.local
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: "{{ item.regexp }}={{ item.val }}"
    backup: "{{ fm_ssmtp_backup_conf }}"
    create: true
  loop: "{{ fm_ssmtp_periodic_conf }}"

# EOF
...
