---

- name: "rcconf: Disable sendmail in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}={{ item.line }}"
    backup: "{{ fm_ssmtp_backup_conf }}"
  loop:
    - { regexp: "sendmail_enable", line: "\"NONE\"" }
    - { regexp: "sendmail_submit_enable", line: "\"NO\"" }
    - { regexp: "sendmail_outbound_enable", line: "\"NO\"" }
    - { regexp: "sendmail_msp_queue_enable", line: "\"NO\"" }
  notify: stop sendmail

# EOF
...
