---

- name: "rcconf: Disable sendmail in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^{{ item.regexp }}="
    line: "{{ item.regexp }}={{ item.val }}"
    backup: "{{ fm_ssmtp_backup_conf }}"
  loop: "{{ fm_ssmtp_rcconf }}"
  notify: stop sendmail

# EOF
...
